### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by bnika** [grammatek/simaromur#142]
Collect normalization issues to fix in 1.4

- [ ] add days and months normalization, call NormalizationDictionaries.periodDict
- [ ] clean all PRIVATE_USE_AREA unicode symbols in normalizeEncoding(). See if that fixes issue reported by Bjarki, where the time '14:59' is read 'einn fjórir tvípunktur ...' on his phone (Galaxy Note 8, Android 9): 
<img width="224" alt="image" src="https://user-images.githubusercontent.com/1185975/203587885-8433dd3c-23de-4540-a447-5182f728c7fe.png">

- [ ] very long URLs with long rows of digits, e.g. for pages where users are logged in (Basecamp, Facebook), can/should we treat them differently than URLs like 'visir.is/sport' or 'vedur.is/skjalftar-og-eldgos/jardskjalftar' ?

**Comment by lumpidu** [comment]
New normalization bug:

```
Play flutti 154.479 farþega í október en á árinu hefur Play flutt 1,3 milljónir farþega og er sætanýtingin á árinu 84,9 prósent.
```

```
play flutti hundrað fimmtíu <sil> og fjögur þúsund fjögur hundruð sjötíu <sil> og farþega í október <sil> en á árinu hefur play flutt ein komma þrjár milljónir farþega <sil> og er sætanýtingin á árinu áttatíu <sil> og fjögur komma níu prósent 
```

Forgot the `9` of number `154.479`

**Comment by lumpidu** [comment]
> 
> Forgot the `9` of number `154.479`

Fixed in 1.4.x

**Comment by lumpidu** [comment]
- `ISK` should be replaced by the long form instead of reading letters
- „Brest­ur á með V 15-22 m/​s suðvest­an­lands um og upp úr há­degi og stend­ur í um 3 klst. => `" brestur á með v fimmtán til tuttugu og tvö m s suðvestanlands um og upp úr hádegi og stendur í um þrjár klukkustundir x.` (2 issues: m/s, x.)
- Stjórn­end­ur Rúv gera ráð fyr­ir því að aug­lýs­inga­tekj­ur stofn­un­ar­inn­ar hækki á þessu ári um 17,4% frá fyrra ári og að út­varps­gjald hækki um 3,5%. => `stjórnendur rúv gera ráð fyrir því að auglýsingatekjur stofnunarinnar hækki á þessu ári um sautján komma fjögur prósent frá fyrra ári og að útvarpsgjald hækki um þrír , fimm prósent .`
- Má áætla að þriðji stóri íþróttaviðburður­inn sem horft hafi verið til sé EM í hand­bolta sem fór fram nú í janú­ar. => `má áætla að þriðji stóri íþróttaviðburðurinn sem horft hafi verið til sé em í handbolta sem fór fram nú í janúar .` (EM)
- ADHD => adhd
- "54. gr. sveita­stjórn­ar­laga nr. 138/​2011 seg­ir að ..." => `fimmtugasta og fjórða grein sveitastjórnarlaga þrírxnúmer einn þrír átta skástrik tvö þúsund og ellefu segir að ...`
- mbl.is/frettir/innlent/2024/02/02/litlu_hlutirnir_sem_folkid_saknar_helst/m => `mbl.is skástrikfrettir skástrikinnlent skástrik tveir núll tveir fjórir skástrik núll tveir skástrik núll tveir skástriklitlu hlutirnir sem folkid saknar helst .` (missing 'punktur', skástrik without space, 2024 not spoken as normal number)
- 3.7 => `þrír. sjö .`
- 13.7 => `einn þrír. sjö .`
- in general: unknown capital letter patterns should be spelled as single letters (space or dash separated): 'ADHD' => 'A D H D`
- 2188¥ => `tveir einn átta átta .`
- 377£ => `þrír sjö sjö .`
- 800€ => `átta núll núll .`
- 9000 ISK => `níu þúsund isk .`
- 456$ => `fjórir fimm sex .`

**Comment by lumpidu** [comment]
fixed
